Algoritmo "Primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luana
// Data atual  : 16/09/2021
Var
// Seção de Declarações das variáveis 
       msg: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         msg <- "Olá, mundo! Me livrei da maldição!"

         Escreval (msg)


Fimalgoritmo